#logback输出日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: log
spring:
  jackson:
    default-property-inclusion: non_null
  front: https://fe-resource.cdn.bcebos.com/phoneTracker/phone-tracker_h5.js
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xbs?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&connectTimeout=5000&socketTimeout=5000&autoReconnect=true&maxReconnects=5&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
   #开启控制台打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
shiro:
  loginUrl: /web/login
